title:              Dev Blog
email:              minjupk@hotmail.com
description:        Tech blog where I put stuff that I find interesting
author:             Minju Park
baseurl:            "/minjupk.github.io"
url:                "https://minjupk.github.io"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    minjupk
# facebook_username:  StartBootstrap
# instagram_username:  
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
